### ISSUE TITLE
Error detected while processing function UltiSnips#TrackChange

### ISSUE THREAD

**Issue by sicaboy** [avelino/vim-bootstrap#261]
When inputting anything, shows the following errors:

Error detected while processing function UltiSnips#TrackChange:                                                                       
line    1:                                                                                                                            
Traceback (most recent call last):                                                                                                    
Press ENTER or type command to continue                                                                                               
Error detected while processing function UltiSnips#TrackChange:                                                                       
line    1:                                                                                                                            
  File "<string>", line 1, in <module>                                                                                                
Press ENTER or type command to continue                                                                                               
Error detected while processing function UltiSnips#TrackChange:                                                                       
line    1:                                                                                                                            
NameError: name 'UltiSnips_Manager' is not defined                                                                                    
Press ENTER or type command to continue                                                                                               
Error detected while processing function UltiSnips#TrackChange:                                                                       
line    1:                                                                                                                            
Traceback (most recent call last):

**Comment by cassiobotaro** [comment]
@sicaboy Please follow our issue guideline: 

1. Please speak English, this is the language everybody of us can speak and write.
2. Please ask questions or config/deploy problems on our Vim Bootstrap channel: https://gitter.im/avelino/vim-bootstrap
3. Please take a moment to search that an issue doesn't already exist.
4. Please give all relevant information below for bug reports, incomplete details will be handled as an invalid report.
5. Please verify if you follow the dependencies instructions on README

**You MUST delete the content above including this line before posting, otherwise your issue will be invalid.**

- Vim bootstrap version(number in first line):
- Operating system:
- Vim/Nvim version:
- Languages:

## Description

Include here an issue description and also a screenshot if possible.

**Comment by sicaboy** [comment]
https://github.com/avelino/vim-bootstrap/issues/206
